kind: Deployment
apiVersion: apps/v1
metadata:
  name: fileserver
  labels:
    app: fileserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileserver
  template:
    metadata:
      labels:
        app: fileserver
    spec:
      containers:
        - name: fileserver
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          volumeMounts:
            - name: static
              mountPath: /usr/share/nginx/html/
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: static
          configMap:
            name: static
---
kind: Service
apiVersion: v1
metadata:
  name: fileserver
  labels:
    app: fileserver
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: fileserver
  type: ClusterIP
  sessionAffinity: None
